package com.gilbeot.gilbut.domain.chat;

public enum ChatState {
    DESTINATION_WAITING,
    ORIGIN_CONFIRMATION,
    HOME_CONFIRMATION,
    DEPARTURE_TIME_CONFIRMATION,
    TODAY_CONDITION_CONFIRMATION,
    ROUTE_CALCULATING,
    STAIR_ROUTE_CONFIRMATION,
    RESULT_PRESENTATION,
    NAVIGATING,
    ARRIVED
}